Improve github actions

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -6,7 +6,7 @@ jobs:
   build:
     env:
       BUILD_CONFIG: Release
-
+      VERSION_SUFFIX: -preview${{ github.run_id }}
     name: Build
     runs-on: ubuntu-latest
     services:
@@ -22,7 +22,7 @@ jobs:
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v1.0.0
       with:
-        version: 3.1.100
+        version: 3.1.201
     - name: dotnet build
       run: dotnet build Esquio.sln -c $BUILD_CONFIG
     - name: dotnet test [UnitTests]
@@ -30,23 +30,31 @@ jobs:
     - name: dotnet test [FunctionalTests]
       run: dotnet test ./tests/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
     - name: dotnet pack [Esquio]
-      run: dotnet pack ./src/Esquio/Esquio.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
+      run: dotnet pack ./src/Esquio/Esquio.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
     - name: dotnet pack [Esquio.AspNetCore]
-      run: dotnet pack ./src/Esquio.AspNetCore/Esquio.AspNetCore.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
+      run: dotnet pack ./src/Esquio.AspNetCore/Esquio.AspNetCore.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
     - name: dotnet pack [Esquio.AspNetCore.ApplicationInsightProcessor]
-      run: dotnet pack ./src/Esquio.AspNetCore.ApplicationInsightProcessor/Esquio.AspNetCore.ApplicationInsightProcessor.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
+      run: dotnet pack ./src/Esquio.AspNetCore.ApplicationInsightProcessor/Esquio.AspNetCore.ApplicationInsightProcessor.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
     - name: dotnet pack [Esquio.Configuration.Store]
-      run: dotnet pack ./src/Esquio.Configuration.Store/Esquio.Configuration.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
-    - name: dotnet pack [Esquio.EntityFrameworkCore.Store]
-      run: dotnet pack ./src/Esquio.EntityFrameworkCore.Store/Esquio.EntityFrameworkCore.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
+      run: dotnet pack ./src/Esquio.Configuration.Store/Esquio.Configuration.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
+    - name: dotnet pack [Esquio.Http.Store]
+      run: dotnet pack ./src/Esquio.Http.Store/Esquio.Http.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
     - name: dotnet pack [Esquio.MiniProfiler]
-      run: dotnet pack  ./tools/Esquio.MiniProfiler/Esquio.MiniProfiler.csproj -c $BUILD_CONFIG --no-build --version-suffix "-nightly" --include-source --include-symbols
+      run: dotnet pack  ./tools/Esquio.MiniProfiler/Esquio.MiniProfiler.csproj -c $BUILD_CONFIG --no-build --version-suffix $VERSION_SUFFIX --include-source --include-symbols
     - name: dotnet pack [Esquio.CLi]
-      run: dotnet pack  ./tools/Esquio.CliTool/Esquio.CliTool.csproj -c $BUILD_CONFIG --no-build --version-suffix "-nightly" --include-source --include-symbols
+      run: dotnet pack  ./tools/Esquio.CliTool/Esquio.CliTool.csproj -c $BUILD_CONFIG --no-build --version-suffix $VERSION_SUFFIX --include-source --include-symbols
     - name: Publish nuget
       run: |
           for f in ./artifacts/*.nupkg
           do
-            curl -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril
+            echo "Publishing $f"
+            curl --silent --show-error --fail -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril/
+            if [ $? -eq 0 ]
+            then
+              echo "successfully pushed $f"
+            else
+              echo "failed to push $f" >&2
+              exit 1
+            fi
           done
       shell: bash
